Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$docsRoot = Split-Path -Parent $scriptDir
$repoRoot = Split-Path -Parent $docsRoot
$srcRoot = Join-Path $repoRoot 'src'

$englishOut = Join-Path $docsRoot 'api/generated'
$chineseOut = Join-Path $docsRoot 'zh/api/generated'
New-Item -ItemType Directory -Force -Path $englishOut, $chineseOut | Out-Null

function Get-PackageSlug([string] $packageName) {
    return $packageName.Replace('HelmSharp.', '').ToLowerInvariant()
}

function Escape-Markdown([string] $value) {
    return $value.Replace('|', '\|')
}

function Get-PublicApi([string] $packageDir) {
    $types = @()
    foreach ($file in Get-ChildItem -Path $packageDir -Filter '*.cs' -Recurse) {
        $relative = [IO.Path]::GetRelativePath($repoRoot, $file.FullName).Replace('\', '/')
        $lines = Get-Content -Path $file.FullName
        $currentType = $null

        foreach ($line in $lines) {
            if ($line -match '^\s*public\s+(?:(sealed|static|abstract)\s+)?(class|interface|record|enum)\s+([A-Za-z_][A-Za-z0-9_]*)') {
                $currentType = [ordered]@{
                    Kind = $matches[2]
                    Name = $matches[3]
                    Source = $relative
                    Properties = New-Object System.Collections.Generic.List[string]
                    Methods = New-Object System.Collections.Generic.List[string]
                }
                $types += [pscustomobject]$currentType
                continue
            }

            if ($null -eq $currentType) {
                continue
            }

            if ($line -match '^\s*public\s+(?:static\s+)?(?:[A-Za-z0-9_<>,\.\?\[\]]+\s+)+([A-Za-z_][A-Za-z0-9_]*)\s*\{\s*get;') {
                $currentType.Properties.Add($matches[1])
                continue
            }

            if ($line -match '^\s*public\s+(?:async\s+)?(?:static\s+)?(?:[A-Za-z0-9_<>,\.\?\[\]]+\s+)+([A-Za-z_][A-Za-z0-9_]*)\s*\(') {
                $currentType.Methods.Add($matches[1])
            }
        }
    }

    return $types | Sort-Object Name
}

function Write-PackageReference(
    [string] $packageName,
    [object[]] $types,
    [string] $path,
    [string] $language) {

    $builder = New-Object System.Text.StringBuilder

    if ($language -eq 'zh') {
        [void]$builder.AppendLine("# $packageName API")
        [void]$builder.AppendLine()
        [void]$builder.AppendLine("> 生成内容。本页由 ``docs/scripts/generate-api-reference.ps1`` 根据公开 C# 声明生成。人工整理的使用建议在对应包页面中维护。")
        [void]$builder.AppendLine()
        [void]$builder.AppendLine("此页列出公开类型和成员，便于查找。使用建议、边界和示例请先阅读对应包文档。")
        [void]$builder.AppendLine()
        [void]$builder.AppendLine("> **版本说明：** 本页反映当前 ``master`` 源码树。M2 API 已包含在最新发布的 1.2.0 包中。")
    }
    else {
        [void]$builder.AppendLine("# $packageName API")
        [void]$builder.AppendLine()
        [void]$builder.AppendLine("> Generated section. This page is generated by ``docs/scripts/generate-api-reference.ps1`` from public C# declarations. Curated usage guidance lives in the package pages.")
        [void]$builder.AppendLine()
        [void]$builder.AppendLine("Use this page as a member index. Start with the package guide for usage recommendations, boundaries, and examples.")
        [void]$builder.AppendLine()
        [void]$builder.AppendLine("> **Version note:** This page reflects the current ``master`` source tree. M2 APIs are available in the latest published 1.2.0 packages.")
    }

    foreach ($type in $types) {
        [void]$builder.AppendLine()
        [void]$builder.AppendLine("## $($type.Name)")
        [void]$builder.AppendLine()
        if ($language -eq 'zh') {
            [void]$builder.AppendLine("| 字段 | 值 |")
        }
        else {
            [void]$builder.AppendLine("| Field | Value |")
        }
        [void]$builder.AppendLine("| --- | --- |")
        if ($language -eq 'zh') {
            [void]$builder.AppendLine("| 类型类别 | ``$($type.Kind)`` |")
            [void]$builder.AppendLine("| 源文件 | ``$($type.Source)`` |")
        }
        else {
            [void]$builder.AppendLine("| Kind | ``$($type.Kind)`` |")
            [void]$builder.AppendLine("| Source | ``$($type.Source)`` |")
        }

        if ($type.Properties.Count -gt 0) {
            [void]$builder.AppendLine()
            [void]$builder.AppendLine($(if ($language -eq 'zh') { "### 属性" } else { "### Properties" }))
            foreach ($property in ($type.Properties | Sort-Object -Unique)) {
                [void]$builder.AppendLine("- ``$(Escape-Markdown $property)``")
            }
        }

        if ($type.Methods.Count -gt 0) {
            [void]$builder.AppendLine()
            [void]$builder.AppendLine($(if ($language -eq 'zh') { "### 方法" } else { "### Methods" }))
            foreach ($method in ($type.Methods | Sort-Object -Unique)) {
                [void]$builder.AppendLine("- ``$(Escape-Markdown $method)(...)``")
            }
        }

        [void]$builder.AppendLine()
        if ($language -eq 'zh') {
            [void]$builder.AppendLine("### 使用提示")
            [void]$builder.AppendLine("先查看对应包页面的场景示例，再使用此成员索引定位具体类型。")
        }
        else {
            [void]$builder.AppendLine("### Usage note")
            [void]$builder.AppendLine("Read the corresponding package page first, then use this member index to locate the concrete type.")
        }
    }

    Set-Content -Path $path -Value $builder.ToString().TrimEnd() -Encoding utf8
}

foreach ($project in Get-ChildItem -Path $srcRoot -Directory -Filter 'HelmSharp.*') {
    $packageName = $project.Name
    $slug = Get-PackageSlug $packageName
    $types = @(Get-PublicApi $project.FullName)
    Write-PackageReference $packageName $types (Join-Path $englishOut "$slug.md") 'en'
    Write-PackageReference $packageName $types (Join-Path $chineseOut "$slug.md") 'zh'
}

Write-Host "Generated API reference pages in $englishOut and $chineseOut."
